# Example tournament configuration

# Agent definitions - name and command to run
agents:
  SimpleRuby: './simple_agent.rb'
  SmartRuby: './smarter_agent.rb'

# Tournament format
# Options: 'round-robin' or 'elimination-bracket'
tournament_type: round-robin

# Number of games per match/round
games_per_round: 200

# Timeout configuration (optional)
timeouts:
  # Time limit per turn in seconds (0 = no limit)
  turn_timeout: 5.0

  # Time limit per game in seconds (0 = no limit)
  game_timeout: 100.0

# Output configuration
output:
  # Show progress on stdout
  stdout: true
  # Log all output to file (optional)
  log_file: logs/tournament_full.log
  # Save just the final results (optional)
  log_results_file: logs/tournament_results.txt
  # Save game plays in semicolon format (optional)
  game_log_file: logs/game_plays.log
