# Example tournament configuration

# Agent definitions - name and command to run
agents:
  SimpleRuby: './simple_agent.rb'
  SmartRuby: './smart_agent.rb'

# Tournament format
# Options: 'round-robin' or 'elimination-bracket'
tournament_type: round-robin

# Number of games per match/round
games_per_round: 40

# Timeout configuration (optional)
timeouts:
  # Time limit per turn in seconds (0 = no limit)
  turn_timeout: 5.0

  # Time limit per game in seconds (0 = no limit)
  game_timeout: 100.0

# Output configuration
output:
  # Show progress on stdout
  stdout: true

  # Log all output to file (optional)
  log_file: tournament_full.log

  # Save just the final results (optional)
  log_results_file: tournament_results.txt
